// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wailsapi} from '../models';

export function AgentStatuses():Promise<Array<wailsapi.AgentInfo>>;

export function Greet(arg1:string):Promise<string>;

export function InstallAgent(arg1:string):Promise<void>;

export function KillAgent(arg1:string,arg2:string):Promise<void>;

export function SendToAgent(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SpawnAgent(arg1:string):Promise<string>;

export function SupportedAgents():Promise<Array<string>>;

export function UninstallAgent(arg1:string):Promise<void>;
