// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AgentStatuses() {
  return window['go']['wailsapi']['API']['AgentStatuses']();
}

export function Greet(arg1) {
  return window['go']['wailsapi']['API']['Greet'](arg1);
}

export function InstallAgent(arg1) {
  return window['go']['wailsapi']['API']['InstallAgent'](arg1);
}

export function KillAgent(arg1, arg2) {
  return window['go']['wailsapi']['API']['KillAgent'](arg1, arg2);
}

export function SendToAgent(arg1, arg2, arg3) {
  return window['go']['wailsapi']['API']['SendToAgent'](arg1, arg2, arg3);
}

export function SpawnAgent(arg1) {
  return window['go']['wailsapi']['API']['SpawnAgent'](arg1);
}

export function SupportedAgents() {
  return window['go']['wailsapi']['API']['SupportedAgents']();
}

export function UninstallAgent(arg1) {
  return window['go']['wailsapi']['API']['UninstallAgent'](arg1);
}
